# FIX #4/#8: Uses optional auth to associate logs with user when token present
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel, Field
from typing import Optional
import random

from database import get_db, DecisionLog, GameSession
from auth_utils import get_current_user_optional

router = APIRouter()

DEEPFAKE_SAMPLES = [
    {
        "id": 1, "type": "image", "label": "AI-Generated",
        "url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
        "title": "Portrait Photo - Is this real?",
        "description": "A man's portrait photo with a neutral background.",
        "clues": [
            "Skin texture appears unnaturally smooth around jaw",
            "Ear details are slightly asymmetric",
            "Background has subtle blur inconsistencies",
            "Hair strands merge unnaturally near the top",
        ],
        "explanation": "Generated by a GAN model. Overly smooth skin texture and slight asymmetry are common GAN artifacts.",
    },
    {
        "id": 2, "type": "image", "label": "Real",
        "url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
        "title": "Social Media Profile Photo",
        "description": "A woman's headshot with natural background.",
        "clues": [
            "Natural skin texture with visible pores",
            "Consistent lighting and shadows",
            "Natural background depth-of-field",
        ],
        "explanation": "A genuine photograph. Natural skin imperfections and authentic background depth-of-field confirm it.",
    },
    {
        "id": 3, "type": "audio", "label": "AI-Generated",
        "url": None,
        "audioText": "Hello, this is your bank calling. Your account has been flagged for suspicious activity. Press 1 to speak to an agent immediately or your account will be frozen in 24 hours.",
        "title": "Voice Message from Bank",
        "description": "A supposed voice message from your bank.",
        "clues": [
            "Robotic inflection on key words like 'immediately'",
            "No ambient background noise — too clean",
            "Unnatural pause lengths between sentences",
            "Voice pitch is perfectly consistent — no human variation",
        ],
        "explanation": "AI voice synthesis creates speech that is too 'perfect'. Real human voices have micro-variations in pitch and natural breathing.",
    },
    {
        "id": 4, "type": "image", "label": "AI-Generated",
        "url": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400",
        "title": "Business Executive Profile",
        "description": "A professional portrait of a business executive.",
        "clues": [
            "Collar and tie alignment appears digitally perfect",
            "Eyes appear slightly too symmetrical",
            "Background elements lack depth coherence",
        ],
        "explanation": "GAN-generated images often produce faces that are 'too perfect'. The symmetry of facial features exceeds what occurs naturally.",
    },
    {
        "id": 5, "type": "image", "label": "Real",
        "url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400",
        "title": "Candid Street Photo",
        "description": "A candid photograph of a person in an urban setting.",
        "clues": [
            "Natural motion blur present",
            "Real-world lighting imperfections",
            "Authentic facial expression with micro-expressions",
        ],
        "explanation": "Genuine photograph captured in natural conditions. Motion blur and lighting inconsistencies confirm authenticity.",
    },
    {
        "id": 6, "type": "audio", "label": "Real",
        "url": None,
        "audioText": "Hi, um, I just wanted to... I called last week about my order and it still hasn't arrived. Can someone please look into this? My order number is, uh, let me check... it's 47892. Thanks.",
        "title": "Customer Feedback Recording",
        "description": "A customer service voicemail recording.",
        "clues": [
            "Natural hesitation and filler words (um, uh)",
            "Realistic memory lapse: 'let me check'",
            "Normal speech rhythm variations",
        ],
        "explanation": "Real speech contains disfluencies, self-corrections, and variable pacing. AI synthesis is typically over-smooth.",
    },
    {
        "id": 7, "type": "image", "label": "AI-Generated",
        "url": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400",
        "title": "Dating App Profile Photo",
        "description": "An attractive portrait photo submitted for profile review.",
        "clues": [
            "Too-perfect facial symmetry",
            "Background elements appear 'painted'",
            "Jewelry details are inconsistently rendered",
            "Teeth are unnaturally uniform",
        ],
        "explanation": "AI romance scam profiles use GAN-generated faces. Perfectly uniform teeth, background artifacts, and hyper-symmetrical features are telltale signs.",
    },
    {
        "id": 8, "type": "video", "label": "AI-Generated",
        "url": None,
        "videoDescription": "A 30-second video of a politician speaking at a press conference. He appears to be announcing a major financial scandal involving his party.",
        "title": "Political Press Conference Clip",
        "description": "A short video clip circulating on social media claiming to show a politician making controversial statements.",
        "clues": [
            "Lip movements don't perfectly sync with audio — especially on 'B' and 'P' sounds",
            "Skin on the neck appears blurred compared to the face",
            "Eye-blink rate is unusually infrequent (deepfakes often miss natural blink patterns)",
            "Background crowd has repeated identical figures — a rendering artifact",
            "Lighting on the face doesn't match the background environment",
        ],
        "explanation": "This is a deepfake video created using face-swapping technology. The tell-tale signs are lip-sync errors, unnatural blinking, and skin texture inconsistencies at the face-neck boundary.",
    },
    {
        "id": 9, "type": "image", "label": "Real",
        "url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
        "title": "Customer Support Agent Photo",
        "description": "A headshot from a company's 'Meet Our Team' page.",
        "clues": [
            "Natural asymmetry in facial features",
            "Background has authentic office environment details",
            "Subtle skin imperfections visible — pores, slight redness",
        ],
        "explanation": "This is a genuine photograph. Natural facial asymmetry, real background depth, and authentic skin texture (with natural imperfections) confirm it.",
    },
    {
        "id": 10, "type": "audio", "label": "AI-Generated",
        "url": None,
        "audioText": "Beta, I'm in a lot of trouble. My phone's battery is dying. I had an accident and need Rs 50,000 immediately. Please send it to this UPI ID right now. Don't tell your father yet. I'll explain everything later.",
        "title": "Urgent Voice Note — Parent in Trouble",
        "description": "A WhatsApp voice message appearing to be from a parent asking for emergency money.",
        "clues": [
            "Voice is slightly more robotic than natural — typical of voice cloning",
            "No background sounds of an accident scene or hospital",
            "The urgent secrecy request ('don't tell father') is a manipulation tactic, not typical parental behaviour",
            "Immediate financial request without verifiable context",
        ],
        "explanation": "This is a voice-cloned scam. Attackers scrape voice samples from social media to clone family members' voices. Always call back directly on a known number before sending money.",
    },
]


class SubmitAnswer(BaseModel):
    sample_id: int = Field(..., ge=1)
    answer: str = Field(..., pattern="^(Real|AI-Generated)$")
    correct: bool
    points: int = Field(..., ge=0, le=50)


@router.get("/samples")
async def get_samples():
    shuffled = DEEPFAKE_SAMPLES.copy()
    random.shuffle(shuffled)
    return {"samples": shuffled}


@router.post("/submit")
async def submit_answer(
    req: SubmitAnswer,
    token_data: Optional[dict] = Depends(get_current_user_optional),
    db: AsyncSession = Depends(get_db),
):
    user_id = int(token_data["sub"]) if token_data else None
    log = DecisionLog(
        user_id=user_id,
        module="deepfake",
        item_id=req.sample_id,
        answer=req.answer,
        correct=req.correct,
        points=req.points,
    )
    db.add(log)
    await db.commit()
    return {"status": "logged", "correct": req.correct, "points": req.points}


@router.post("/session")
async def save_session(
    score: int = 0,
    correct: int = 0,
    total: int = 0,
    token_data: Optional[dict] = Depends(get_current_user_optional),
    db: AsyncSession = Depends(get_db),
):
    user_id = int(token_data["sub"]) if token_data else None
    session = GameSession(user_id=user_id, module="deepfake", score=score, correct=correct, total=total)
    db.add(session)
    await db.commit()
    return {"status": "saved"}
