import React, { useState, useEffect, useCallback } from "react";
import { useApp } from "../App";
import { Eye, CheckCircle, XCircle, ChevronRight, AlertTriangle, RotateCcw, Info, Film } from "lucide-react";
import toast from "react-hot-toast";
import api from "../utils/api";
import { useScoreSound, ScoreFloat } from "../utils/wow";

const LOCAL_SAMPLES = [
  {
    id: 1, type: "image", label: "AI-Generated",
    url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    title: "Portrait Photo - Is this real?",
    description: "A man's portrait photo with a neutral background.",
    clues: ["Skin texture appears unnaturally smooth around jaw", "Ear details are slightly asymmetric", "Background has subtle blur inconsistencies", "Hair strands merge unnaturally near the top"],
    explanation: "Generated by a GAN model. Overly smooth skin texture and slight facial asymmetry are the most common deepfake artifacts.",
  },
  {
    id: 2, type: "image", label: "Real",
    url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400",
    title: "Social Media Profile Photo",
    description: "A woman's headshot with a natural background.",
    clues: ["Natural skin texture with visible pores", "Consistent lighting and shadow direction", "Natural background depth-of-field"],
    explanation: "A genuine photograph. Natural skin imperfections and authentic background depth-of-field confirm it.",
  },
  {
    id: 3, type: "audio", label: "AI-Generated",
    url: null,
    audioText: "Hello, this is your bank calling. Your account has been flagged for suspicious activity. Press 1 to speak to an agent immediately or your account will be frozen in 24 hours.",
    title: "Voice Message from Bank",
    description: "A supposed voice message from your bank.",
    clues: ["Robotic inflection on key words like 'immediately'", "No ambient background noise — unnaturally clean", "Unnatural pause lengths between sentences", "Voice pitch is perfectly consistent — no human variation"],
    explanation: "AI voice synthesis creates speech that is too 'perfect'. Real human voices have micro-variations in pitch and natural breathing.",
  },
  {
    id: 4, type: "image", label: "AI-Generated",
    url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400",
    title: "Business Executive Profile",
    description: "A professional portrait of a business executive.",
    clues: ["Collar and tie alignment appears digitally perfect", "Eyes appear slightly too symmetrical", "Background elements lack depth coherence"],
    explanation: "GAN-generated images often produce faces that are 'too perfect'. Facial symmetry exceeds what occurs naturally.",
  },
  {
    id: 5, type: "image", label: "Real",
    url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400",
    title: "Candid Street Photo",
    description: "A candid photograph of a person in an urban setting.",
    clues: ["Natural motion blur present", "Real-world lighting imperfections", "Authentic facial expression with micro-expressions"],
    explanation: "Genuine photograph captured in natural conditions. Motion blur and lighting inconsistencies confirm authenticity.",
  },
  {
    id: 6, type: "audio", label: "Real",
    url: null,
    audioText: "Hi, um, I just wanted to... I called last week about my order and it still hasn't arrived. Can someone please look into this? My order number is, uh, let me check... it's 47892. Thanks.",
    title: "Customer Feedback Recording",
    description: "A customer service voicemail recording.",
    clues: ["Natural hesitation and filler words (um, uh)", "Realistic memory lapse: 'let me check'", "Variable speech rhythm and pacing"],
    explanation: "Real speech contains disfluencies, self-corrections, and variable pacing. AI synthesis is typically over-smooth.",
  },
  {
    id: 7, type: "image", label: "AI-Generated",
    url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400",
    title: "Dating App Profile Photo",
    description: "An attractive portrait photo.",
    clues: ["Too-perfect facial symmetry", "Background elements appear 'painted'", "Jewelry details are inconsistently rendered", "Teeth are unnaturally uniform"],
    explanation: "AI romance scam profiles use GAN-generated faces. Perfectly uniform teeth, background artifacts, and hyper-symmetrical features are telltale signs.",
  },
  {
    id: 8, type: "video", label: "AI-Generated",
    url: null,
    videoDescription: "A 30-second video of a politician speaking at a press conference, appearing to announce a major financial scandal.",
    title: "Political Press Conference Clip",
    description: "A short video clip circulating on social media claiming to show a politician making controversial statements.",
    clues: ["Lip movements don't perfectly sync with audio — especially on 'B' and 'P' sounds", "Skin on the neck appears blurred compared to the face", "Eye-blink rate is unusually infrequent — deepfakes often miss natural blink patterns", "Background crowd has repeated identical figures — a rendering artifact", "Lighting on the face doesn't match the background environment"],
    explanation: "This is a deepfake video. The tell-tale signs are lip-sync errors, unnatural blinking, and skin texture inconsistencies at the face-neck boundary.",
  },
  {
    id: 9, type: "image", label: "Real",
    url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
    title: "Customer Support Agent Photo",
    description: "A headshot from a company's 'Meet Our Team' page.",
    clues: ["Natural asymmetry in facial features", "Background has authentic office environment details", "Subtle skin imperfections visible — pores, slight redness"],
    explanation: "Genuine photograph. Natural facial asymmetry, real background depth, and authentic skin texture confirm it.",
  },
  {
    id: 10, type: "audio", label: "AI-Generated",
    url: null,
    audioText: "Beta, I'm in a lot of trouble. My phone's battery is dying. I had an accident and need Rs 50,000 immediately. Please send it to this UPI ID right now. Don't tell your father yet. I'll explain everything later.",
    title: "Urgent Voice Note — Parent in Trouble",
    description: "A WhatsApp voice message appearing to be from a parent asking for emergency money.",
    clues: ["Voice is slightly more robotic than natural — typical of voice cloning", "No background sounds of an accident scene or hospital", "The urgent secrecy request ('don't tell father') is a manipulation tactic", "Immediate financial request without verifiable context"],
    explanation: "This is a voice-cloned scam. Attackers scrape voice samples from social media to clone family members' voices. Always call back directly on a known number before sending money.",
  },
];

export default function DeepfakeDetective() {
  const { updateScore, addHistory } = useApp();
  const { playCorrect, playWrong } = useScoreSound();
  const [floatPts, setFloatPts]       = useState(0);
  const [floatVisible, setFloatVisible] = useState(false);
  const [shakeRow, setShakeRow]         = useState(false);
  const [samples, setSamples]               = useState(LOCAL_SAMPLES);
  const [currentIdx, setCurrentIdx]         = useState(0);
  const [answered, setAnswered]             = useState(false);
  const [userChoice, setUserChoice]         = useState(null);
  const [results, setResults]               = useState([]);
  const [finished, setFinished]             = useState(false);
  const [showAttackerView, setShowAttackerView] = useState(false);

  useEffect(() => {
    api.get("/api/deepfake/samples")
      .then(res => { if (res.data?.samples?.length) setSamples(res.data.samples); })
      .catch(() => {});
  }, []);

  useEffect(() => {
    if (!finished || results.length === 0) return;
    const correctCount = results.filter(r => r.correct).length;
    api.post("/api/deepfake/session", null, {
      params: { score: correctCount * 15, correct: correctCount, total: results.length }
    }).catch(() => {});
  }, [finished, results]);

  const current      = samples[currentIdx];
  const totalSamples = samples.length;

  const handleAnswer = useCallback(async (choice) => {
    if (answered || !current) return;
    setUserChoice(choice);
    setAnswered(true);
    const correct = choice === current.label;
    const points  = correct ? 15 : 0;
    if (correct) {
      updateScore("deepfake", points);
      playCorrect();
      setFloatPts(points); setFloatVisible(true);
      setTimeout(() => setFloatVisible(false), 950);
    } else {
      playWrong();
      setShakeRow(true);
      setTimeout(() => setShakeRow(false), 500);
    }
    addHistory({ label: `Deepfake: ${current.title}`, correct, points, module: "deepfake" });
    setResults(prev => [...prev, { id: current.id, correct, choice, label: current.label, title: current.title }]);
    api.post("/api/deepfake/submit", { sample_id: current.id, answer: choice, correct, points }).catch(() => {});
  }, [answered, current, updateScore, addHistory]);

  const handleNext = useCallback(() => {
    if (currentIdx + 1 >= totalSamples) { setFinished(true); return; }
    setCurrentIdx(i => i + 1);
    setAnswered(false);
    setUserChoice(null);
    setShowAttackerView(false);
  }, [currentIdx, totalSamples]);

  const handleRestart = useCallback(() => {
    setCurrentIdx(0); setAnswered(false); setUserChoice(null);
    setResults([]); setFinished(false); setShowAttackerView(false);
  }, []);

  if (finished) {
    const correctCount = results.filter(r => r.correct).length;
    const pct = results.length > 0 ? Math.round((correctCount / results.length) * 100) : 0;
    return <ResultScreen correct={correctCount} total={results.length} pct={pct} results={results} onRestart={handleRestart} />;
  }

  if (!current) return null;

  return (
    <div className="p-6 max-w-2xl mx-auto animate-fade-in">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center">
          <Eye size={20} className="text-blue-600" />
        </div>
        <div>
          <h2 className="font-display font-bold text-neutral-900 text-lg">Deepfake Detective</h2>
          <p className="text-xs text-neutral-400">Sample {currentIdx + 1} of {totalSamples}</p>
        </div>
        <div className="ml-auto text-sm font-medium text-neutral-500">
          {results.filter(r => r.correct).length}/{results.length} correct
        </div>
      </div>

      <div className="progress-bar mb-6">
        <div className="progress-fill" style={{ width: `${(currentIdx / totalSamples) * 100}%` }} />
      </div>

      <div key={currentIdx} className="card overflow-hidden mb-4 animate-fade-in">
        {/* Sample display */}
        <div className="bg-neutral-100 relative min-h-[160px] flex items-center justify-center">
          {current.type === "image" && current.url ? (
            <img src={current.url} alt="Sample to classify" className="w-full h-64 object-cover" loading="lazy" />
          ) : current.type === "audio" ? (
            <div className="w-full h-44 flex flex-col items-center justify-center gap-3 px-6">
              <div className="w-12 h-12 bg-white rounded-full flex items-center justify-center shadow-sm">
                <div className="flex items-end gap-0.5 h-5">
                  {[3,5,7,5,4,6,3,5,7,4].map((h,i) => (
                    <div key={i} className="w-1 bg-primary-400 rounded-full animate-pulse" style={{ height: `${h*3}px`, animationDelay: `${i*0.1}s` }} />
                  ))}
                </div>
              </div>
              <div className="bg-white rounded-xl p-4 shadow-sm max-w-sm w-full">
                <p className="text-xs text-neutral-400 mb-1 font-semibold uppercase tracking-wide">Transcript</p>
                <p className="text-sm text-neutral-700 leading-relaxed italic">"{current.audioText}"</p>
              </div>
            </div>
          ) : current.type === "video" ? (
            <div className="w-full h-52 flex flex-col items-center justify-center gap-3 px-6">
              <div className="w-14 h-14 bg-white rounded-full flex items-center justify-center shadow-sm">
                <Film size={24} className="text-primary-500" />
              </div>
              <div className="bg-white rounded-xl p-4 shadow-sm max-w-sm w-full">
                <p className="text-xs text-neutral-400 mb-1 font-semibold uppercase tracking-wide">Video Description</p>
                <p className="text-sm text-neutral-700 leading-relaxed">{current.videoDescription}</p>
              </div>
            </div>
          ) : null}

          <div className="absolute top-3 right-3 bg-white/90 backdrop-blur-sm px-2.5 py-1 rounded-lg text-xs font-medium text-neutral-600 border border-neutral-200 capitalize">
            {current.type} Sample
          </div>
        </div>

        <div className="p-5">
          <h3 className="font-semibold text-neutral-900 mb-1">{current.title}</h3>
          <p className="text-sm text-neutral-500 mb-4">{current.description}</p>

          {!answered ? (
            <div>
              <p className="text-sm font-medium text-neutral-700 mb-3">Is this content real or AI-generated?</p>
              <div className={`flex gap-3 relative ${shakeRow ? "shake-row" : ""}`}>
                <ScoreFloat points={floatPts} visible={floatVisible} />
                <button onClick={() => handleAnswer("Real")} className="flex-1 py-3 rounded-xl border-2 border-success-200 bg-success-50 text-success-700 font-semibold text-sm hover:bg-success-100 transition-all hover:border-success-400 active:scale-95">Real</button>
                <button onClick={() => handleAnswer("AI-Generated")} className="flex-1 py-3 rounded-xl border-2 border-danger-200 bg-danger-50 text-danger-700 font-semibold text-sm hover:bg-danger-100 transition-all hover:border-danger-400 active:scale-95">AI-Generated</button>
              </div>
            </div>
          ) : (
            <div className="animate-slide-up">
              <div className={`flex items-start gap-3 p-4 rounded-xl mb-4 ${userChoice === current.label ? "feedback-correct" : "feedback-wrong"}`}>
                {userChoice === current.label ? <CheckCircle size={18} className="text-success-600 flex-shrink-0 mt-0.5" /> : <XCircle size={18} className="text-danger-600 flex-shrink-0 mt-0.5" />}
                <div>
                  <p className={`text-sm font-semibold ${userChoice === current.label ? "text-success-700" : "text-danger-700"}`}>
                    {userChoice === current.label ? "Correct! +15 points" : `Incorrect. It was ${current.label}.`}
                  </p>
                  <p className="text-xs mt-1 text-neutral-600">{current.explanation}</p>
                </div>
              </div>

              <div className="mb-4">
                <p className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <Info size={12} /> Detection Clues
                </p>
                <ul className="space-y-1.5">
                  {current.clues.map((c, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs text-neutral-600">
                      <AlertTriangle size={11} className="text-warning-500 flex-shrink-0 mt-0.5" />{c}
                    </li>
                  ))}
                </ul>
              </div>

              <button onClick={() => setShowAttackerView(s => !s)} className="w-full text-left text-xs font-medium text-primary-600 hover:text-primary-800 mb-3 flex items-center gap-1">
                {showAttackerView ? "Hide" : "Show"} Attacker Perspective
                <ChevronRight size={12} className={`transition-transform ${showAttackerView ? "rotate-90" : ""}`} />
              </button>
              {showAttackerView && (
                <div className="bg-neutral-800 text-neutral-200 rounded-xl p-4 text-xs leading-relaxed mb-4 font-mono whitespace-pre-wrap">
                  <p className="text-yellow-400 font-bold mb-2">// Attacker Strategy</p>
                  {current.label === "AI-Generated"
                    ? "// Tools: Stable Diffusion / DALL-E / ElevenLabs / FaceSwap\n// Goal: Impersonate trusted individual or create disinformation\n// Method: Generate realistic media to bypass trust\n// Red flags: Too-perfect features, synthetic patterns, context mismatch"
                    : "// This content is genuine\n// No manipulation detected\n// Trust verification: PASSED"}
                </div>
              )}
              <button onClick={handleNext} className="btn-primary w-full justify-center flex items-center gap-2">
                {currentIdx + 1 >= totalSamples ? "See Results" : "Next Sample"}<ChevronRight size={15} />
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function ResultScreen({ correct, total, pct, results, onRestart }) {
  const grade      = pct >= 80 ? "Excellent" : pct >= 60 ? "Good" : pct >= 40 ? "Fair" : "Needs Work";
  const gradeColor = pct >= 80 ? "text-success-600" : pct >= 60 ? "text-primary-600" : pct >= 40 ? "text-warning-600" : "text-danger-600";
  return (
    <div className="p-6 max-w-lg mx-auto animate-fade-in">
      <div className="card p-8 text-center mb-4">
        <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4"><Eye size={28} className="text-blue-600" /></div>
        <h2 className="font-display font-bold text-neutral-900 text-xl mb-1">Deepfake Detective Complete</h2>
        <p className={`text-4xl font-display font-bold mt-4 mb-1 ${gradeColor} animate-badge-pop`}>{pct}%</p>
        <p className={`text-sm font-semibold ${gradeColor} mb-4`}>{grade}</p>
        <p className="text-neutral-500 text-sm">{correct} of {total} correct — {correct * 15} points earned</p>
      </div>
      <div className="card p-5 mb-4">
        <h3 className="text-sm font-semibold text-neutral-700 mb-3">Question Breakdown</h3>
        <div className="space-y-2">
          {results.map((r, i) => (
            <div key={i} className="flex items-center gap-3 text-sm">
              {r.correct ? <CheckCircle size={15} className="text-success-500 flex-shrink-0" /> : <XCircle size={15} className="text-danger-500 flex-shrink-0" />}
              <span className="flex-1 text-neutral-600 truncate">{r.title}</span>
              <span className="text-xs text-neutral-400">{r.label}</span>
            </div>
          ))}
        </div>
      </div>
      <div className="card p-5 mb-4 bg-blue-50 border border-blue-100">
        <h3 className="text-sm font-semibold text-blue-800 mb-2">Key Learnings</h3>
        <ul className="space-y-1.5 text-xs text-blue-700">
          <li>- Look for overly symmetric facial features in AI portraits</li>
          <li>- Real speech has natural hesitation, filler words, and varied pacing</li>
          <li>- Deepfake videos show lip-sync errors and unnatural blinking</li>
          <li>- Voice clones lack ambient background sounds and human breathing</li>
          <li>- Always verify by calling back on a known number before sending money</li>
        </ul>
      </div>
      <button onClick={onRestart} className="btn-primary w-full justify-center flex items-center gap-2"><RotateCcw size={15} /> Retry Module</button>
    </div>
  );
}
